### ISSUE TITLE
Context Menu example only works in Firefox

### ISSUE THREAD

**Issue by tourdedave** [tourdedave/the-internet#12]
http://the-internet.herokuapp.com/context_menu

It is currently built using the HTML5 menuitem approach (e.g., like [this](http://blog.teamtreehouse.com/building-html5-context-menus)). Consider making it work for all browsers by leveraging [jQuery-contextMenu](https://github.com/medialize/jQuery-contextMenu).

**Comment by Rahdiel** [comment]
It's not working at all. Anywhere.

![obraz](https://user-images.githubusercontent.com/25134673/35228817-f8b2d8b0-ff91-11e7-987f-99fcf9a0d1fc.png)

**Comment by tourdedave** [comment]
Hrm, strange. I'm using Quantum too, and it works fine. Can you provide a screenshot of the context menu that appears when you right click in the dashed box? If it's not working, then you will still see a right-click menu appear, it just won't have an option saying "the-internet" listed.

**Comment by Rahdiel** [comment]
Just reinstalled, it's fine now:) Sorry, for false alarm.

**Comment by tourdedave** [comment]
No worries. Glad to hear you're all set.

**Comment by hkleow** [comment]
Not working here. i'm using firefox quantum as well. any idea? :/

<img width="1279" alt="screen shot 2018-07-07 at 12 05 51 am" src="https://user-images.githubusercontent.com/15167345/42388897-8e177c3a-8179-11e8-8940-5aabf0066a16.png">

**Comment by 0xC4N1** [comment]
@tourdedave according to the [description](https://github.com/tourdedave/the-internet/blob/e86526360e02f035d22b3c4accbcd4b667d4c331/views/context_menu.erb#L4) and the [How To Right Click article](http://elementalselenium.com/tips/63-right-click) it is supposed to open a context menu with a `the-internet` entry and if you select it, an alert should appear. Since 8772ecc it just opens an alert when you context click it. The menu entry is gone.
