### ISSUE TITLE
Challenging DOM: dedicated button not always visible

### ISSUE THREAD

**Issue by rbri** [tourdedave/the-internet#19]
Hi,
some days ago i found your great website. Nice to see that somebody offers
*An example application that captures prominent and ugly functionality found on the web. Perfect for writing automated acceptance tests against.*

So i started to build some WETATOR Tests (www.wetator.org). With the 'Challenging DOM' page i have faced a problem:
A test assumes the a specific button is available on the page. The challenge usually is to find the correct one. But your page is a bit to random from my point of view. A real application always had a defined state - means a button is available or not.
What i like to suggest:
Stay with the random placement, coloring etc. of the buttons but take care, that always the same buttons (by label) are available (e.g. 'foo', 'bar', and 'qux').
What do you think?

    RBRi

**Comment by tourdedave** [comment]
That wouldn't make it a very challenging DOM (hence the example name). The point of the changing labels is to mimic behavior people often found when trying to automate web applications that use unique, dynamically generated IDs that are constantly changing.

**Comment by rbri** [comment]
Hi,
not sure i got your point.
To make it more clear: I only talk about the buttons. And i only like to suggest to have always the same button labels visible on the page (shuffle the order, shuffle the id's and names....). You are right that in many app the button id's are changing per request or per layout change done by the developers. But i think the button labels are are more constant. I guess otherwise the user might get angry.

**Comment by rbri** [comment]
And one more point,
if you like to proof that the test tool does the right thing, it will be great if the page gives some feedback about the clicked action (e.g. if you click edit for the row containing 'Iuvaret1' it will be nice to see some feedback like 'Edit Iuvaret1' somewhere on the page.

**Comment by tourdedave** [comment]
Relying on the text of a label is problematic for an automated test. It's very likely to change. The point of this example is to demonstrate a challenging set of elements to test. That's why there's also a canvas element on the page. If your tool is unable to work with what's there, then the example is working correctly and doesn't require changing.

**Comment by rbri** [comment]
> Relying on the text of a label is problematic for an automated test. It's very likely to change.

So you think the test tool should be able to find e.g. a button based on the action the button triggers? I think a test tool should behave like a real user of the application. At least for the applications i had to write, the real end user will blame me, if i change the label of the 'Save' button to e.g. 'Persist'.

Another option will be to replace the label text of the button with an icon.

**Comment by tourdedave** [comment]
That's right, the goal is to test the application like a user would. But relying on potentially brittle locators is bad practice. If you're both building and testing the front-end then you have the luxury of being able to know when these things will change and you can also change them to be more testable. In that scenario, sure, then what you are recommending is a plausible solution. But that's typically not how things play out in software development situations I've worked in or consulted on.

This example has a purpose, and it is serving it. If you want to change the example to meet your needs then you're free to fork the project, change it on your own, and maintain those changes yourself.

**Comment by rbri** [comment]
Ok, enlighte me. What is less brittle than the label on the button.

**Comment by tourdedave** [comment]
The button of the example in question? There's nothing that's not brittle with it. __That is the point of the example.__

Good locators are unique, descriptive, and unlikely to change. The best place to start is with ID and class attributes since they are the most likely candidates to fit this criteria and are typically the most performant with tools like Selenium. If these attributes don't have helpful names (e.g., dynamic IDs, etc.) then something like a label on a button *could* be something helpful. But *it depends*.

This issue is closed and the feature is not going to be altered. Please refrain from cluttering up the comments of my issue tracker with arguments.

**Comment by tourdedave** [comment]
For additional context: This example was really meant for automated visual testing (just like [shifting content](http://the-internet.herokuapp.com/shifting_content), [dynamic content](http://the-internet.herokuapp.com/dynamic_content), and [floating menu](http://the-internet.herokuapp.com/floating_menu). It's intent was to demonstrate that there are no layout anomalies occurring even though things are constantly changing with it and there are things on the page that are hard to interact with.

At this point it's meant as more of an example of what not to do in an app rather than being something useful for writing a test against. Arguably, you're correct. Making a small change to the labels of the buttons could make this something someone could write tests against more easily. But it's really not a great example to begin with in that context. You're better off using a more targeted example that demonstrates working with elements on a page. If there's not an example on the-internet that meets that criteria then feel free to submit a pull request to add it, or submit an issue to request it.
